export const menu = [
    {
        id: 1,
        title: "Phad-see-ew",
        price: 5.00,
        category: "breakfast",
        img: "./img/padseeew.jpeg",
        desc: "Wok-fried Flat Noodles with Kale, Carrot and Oyster Sauce choice of: Chicken or Pork",
    },
    {
        id: 2,
        title: "Phad Ga-Prao",
        price: 6.00,
        category: "breakfast",
        img: "./img/pad-kra-pao.jpeg",
        desc: "Stir-fried Pork or Chicken or Seafood with Holy Basil Leaves and Fresh Chili",
    },
    {
        id: 3,
        title: "Phad Phak Boong Fai Daeng",
        price: 8.00,
        category: "breakfast",
        img: "./img/pad-pak-bung-fai.jpeg",
        desc: "Wok-fried Morning Glory with Garlic, Fresh Chili and Oyster Sauce",
    },
    {
        id: 4,
        title: "Khaw Phad",
        price: 6.00,
        category: "breakfast",
        img: "./img/Thai-Fried-Rice.jpeg",
        desc: "Fried Rice Served with Fried Egg, choice of: Chicken or Pork",
    },
    {
        id: 5,
        title: "Pad Thai",
        price: 10.00,
        category: "lunch",
        img: "./img/phadtai.jpeg",
        desc: "The most famous Thai noodles stir-fried with chicken, shrimp, egg, bean sprouts, ground peanuts and scallions",
    },
    {
        id: 6,
        title: "Pad See You",
        price: 12.00,
        category: "lunch",
        img: "./img/passeeyou.jpeg",
        desc: "Thai style fl at noodle stir-fried with chicken, shrimp, egg, broccoli and carrots",
    },
    {
        id: 7,
        title: "Lad Na",
        price: 15.00,
        category: "lunch",
        img: "./img/ladna.jpeg",
        desc: "Stir-fried fl at noodle with egg and topped with Thai gravy sauce - with Chinese broccoli, carrots, mushrooms and broccoli.",
    },
    {
        id: 8,
        title: "Pho Beef Noodle",
        pric8: 10.00,
        category: "lunch",
        img: "./img/phobeef.jpeg",
        desc: "Rice noodles with beef, bean sprouts, basil leaves and garnish with scallions and cilantro in beef broth.",
    },
    {
        id: 9,
        title: "Thai Iced Coffee",
        pric8: 3.00,
        category: "drinks",
        img: "./img/iced-coffee-2.png",
        desc: "Fresh coffe with ice.",
    },
    {
        id: 10,
        title: "Thai Iced Tea",
        pric8: 3.50,
        category: "drinks",
        img: "./img/icedtea.jpeg",
        desc: "Special Thai tea with ice.",
    },
    {
        id: 11,
        title: "Apple Juice",
        pric8: 2.00,
        category: "drinks",
        img: "./img/Apple-Juice-Square.jpeg",
        desc: "Fresh Apple Juice.",
    }
]